DROP VIEW "public"."effective_restakes_view";--> statement-breakpoint
DROP VIEW "public"."point_with_details_view";--> statement-breakpoint
DROP VIEW "public"."point_favor_history";--> statement-breakpoint
ALTER TABLE "negations" DROP CONSTRAINT "negations_older_point_id_points_id_fk";
--> statement-breakpoint
ALTER TABLE "negations" DROP CONSTRAINT "negations_newer_point_id_points_id_fk";
--> statement-breakpoint
ALTER TABLE "negations" DROP CONSTRAINT "negations_created_by_users_id_fk";
--> statement-breakpoint
ALTER TABLE "negations" DROP CONSTRAINT "negations_space_spaces_space_id_fk";
--> statement-breakpoint
ALTER TABLE "negations" DROP CONSTRAINT "negations_deleted_by_users_id_fk";
--> statement-breakpoint
ALTER TABLE "slash_history" DROP CONSTRAINT "slash_history_user_id_users_id_fk";
--> statement-breakpoint
ALTER TABLE "slashes" DROP CONSTRAINT "slashes_user_id_users_id_fk";
--> statement-breakpoint
ALTER TABLE "negations" ALTER COLUMN "id" SET DATA TYPE integer;--> statement-breakpoint
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_sequences WHERE sequencename = 'negations_id_seq') THEN
        ALTER TABLE "negations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "negations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);
    END IF;
END $$;--> statement-breakpoint
ALTER TABLE "negations" ALTER COLUMN "older_point_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "negations" ALTER COLUMN "newer_point_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "slash_history" ALTER COLUMN "user_id" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "slashes" ALTER COLUMN "user_id" SET DATA TYPE varchar(255);--> statement-breakpoint
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'slashes' AND column_name = 'space') THEN
        ALTER TABLE "slashes" ADD COLUMN "space" varchar(100);
        UPDATE "slashes" SET "space" = (
          SELECT "space" FROM "points" WHERE "points"."id" = "slashes"."point_id" LIMIT 1
        ) WHERE "space" IS NULL;
        ALTER TABLE "slashes" ALTER COLUMN "space" SET NOT NULL;
    END IF;
END $$;--> statement-breakpoint
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'slash_history_user_id_users_id_fk') THEN
        ALTER TABLE "slash_history" ADD CONSTRAINT "slash_history_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
    END IF;
END $$;--> statement-breakpoint
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'slashes_space_spaces_space_id_fk') THEN
        ALTER TABLE "slashes" ADD CONSTRAINT "slashes_space_spaces_space_id_fk" FOREIGN KEY ("space") REFERENCES "public"."spaces"("space_id") ON DELETE cascade ON UPDATE no action;
    END IF;
END $$;--> statement-breakpoint
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'slashes_user_id_users_id_fk') THEN
        ALTER TABLE "slashes" ADD CONSTRAINT "slashes_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
    END IF;
END $$;--> statement-breakpoint
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'slashes_space_idx') THEN
        CREATE INDEX "slashes_space_idx" ON "slashes" USING btree ("space");
    END IF;
END $$;--> statement-breakpoint
CREATE VIEW "public"."effective_restakes_view" AS (select "user_id", "point_id", "negation_id", "amount", "space", "created_at", 
        COALESCE((
          SELECT "amount"
          FROM "slashes"
          WHERE "restake_id" = "id"
          AND "amount" > 0 
          AND "created_at" > "created_at"
        ), 0)
       as "slashed_amount", 
        COALESCE((
          SELECT SUM("amount")
          FROM "doubts"
          WHERE "point_id" = "point_id"
          AND "negation_id" = "negation_id"
          AND "created_at" >= "created_at"
        ), 0)
       as "doubted_amount", 
        GREATEST(0, "amount" - 
          COALESCE((
            SELECT "amount"
            FROM "slashes"
            WHERE "restake_id" = "id"
            AND "amount" > 0 
            AND "created_at" > "created_at"
          ), 0)
        )
       as "effective_amount", 
        "amount" > COALESCE((
          SELECT "amount"
          FROM "slashes"
          WHERE "restake_id" = "id"
          AND "amount" > 0 
          AND "created_at" > "created_at"
        ), 0)
       as "available_for_doubts" from "restakes" where "restakes"."amount" > 0);--> statement-breakpoint
CREATE VIEW "public"."point_with_details_view" AS (select "id", "content", "created_at", "created_by", "space", "is_command", "is_active", "deleted_at", "deleted_by", 
        COALESCE((
          SELECT COUNT(*)
          FROM (
            SELECT older_point_id AS point_id FROM "negations"
            WHERE "is_active" = true
            UNION ALL
            SELECT newer_point_id AS point_id FROM "negations"
            WHERE "is_active" = true
          ) sub
          WHERE point_id = "points".id
        ), 0)
       as "amount_negations", 
        COALESCE((
          SELECT COUNT(DISTINCT "user_id")
          FROM "endorsements"
          WHERE "point_id" = "points".id
        ), 0)
       as "amount_supporters", 
        COALESCE((
          SELECT SUM("cred")
          FROM "endorsements"
          WHERE "point_id" = "points".id
        ), 0)
       as "cred", 
        COALESCE((
          SELECT SUM("cred")
          FROM "endorsements"
          WHERE "point_id" IN (
            SELECT newer_point_id
            FROM "negations"
            WHERE older_point_id = "points".id
            AND "is_active" = true
            UNION
            SELECT older_point_id
            FROM "negations"
            WHERE newer_point_id = "points".id
            AND "is_active" = true
          )
        ), 0)
       as "negations_cred", 
          ARRAY(
            SELECT older_point_id
            FROM "negations"
            WHERE newer_point_id = "points".id
            AND "is_active" = true
            UNION
            SELECT newer_point_id
            FROM "negations"
            WHERE older_point_id = "points".id
            AND "is_active" = true
          )
         as "negation_ids" from "points" where "points"."is_active" = true);--> statement-breakpoint
CREATE VIEW "public"."point_favor_history" AS 
WITH all_events AS (
  SELECT id as point_id, created_at as event_time, 'point_created'::text as event_type
  FROM points
  UNION ALL
  SELECT point_id, created_at, 'endorsement_made'
  FROM endorsements
  UNION ALL
  SELECT older_point_id, created_at, 'negation_made'
  FROM negations
  UNION ALL
  SELECT newer_point_id, created_at, 'negation_made'
  FROM negations
  UNION ALL
  SELECT restakes.point_id, restake_history.created_at, 'restake_modified'
  FROM restake_history
  JOIN restakes ON restakes.id = restake_history.restake_id
  UNION ALL
  SELECT restakes.point_id, slash_history.created_at, 'slash_modified'
  FROM slash_history
  JOIN slashes ON slashes.id = slash_history.slash_id
  JOIN restakes ON restakes.id = slashes.restake_id
  UNION ALL
  SELECT doubts.point_id, doubt_history.created_at, 'doubt_modified'
  FROM doubt_history
  JOIN doubts ON doubts.id = doubt_history.doubt_id
  UNION ALL
  SELECT id, NOW(), 'favor_queried'
  FROM points
)
SELECT 
  ae.point_id,
  ae.event_type,
  ae.event_time,
  COALESCE((
    SELECT SUM(cred)
    FROM endorsements
    WHERE point_id = ae.point_id
    AND created_at <= ae.event_time
  ), 0) as cred,
  COALESCE((
    SELECT SUM(cred)
    FROM endorsements
    WHERE point_id IN (
      SELECT newer_point_id FROM negations WHERE older_point_id = ae.point_id
      AND created_at <= ae.event_time
      UNION
      SELECT older_point_id FROM negations WHERE newer_point_id = ae.point_id
      AND created_at <= ae.event_time
    )
    AND created_at <= ae.event_time
  ), 0) as negations_cred,
  COALESCE((
    SELECT SUM(rh.new_amount)
    FROM restake_history rh
    JOIN restakes r ON r.id = rh.restake_id
    WHERE r.point_id = ae.point_id
    AND rh.created_at <= ae.event_time
  ), 0) as total_restakes,
  COALESCE((
    SELECT SUM(
      LEAST(
        dh.new_amount,
        (
          SELECT COALESCE(SUM(rh2.new_amount), 0)
          FROM restake_history rh2
          JOIN restakes r2 ON r2.id = rh2.restake_id
          WHERE r2.point_id = ae.point_id
          AND rh2.created_at <= dh.created_at
        )
      )
    )
    FROM doubt_history dh
    JOIN doubts d ON d.id = dh.doubt_id
    WHERE d.point_id = ae.point_id
    AND dh.created_at <= ae.event_time
  ), 0)::integer as effective_doubts,
  COALESCE((
    SELECT SUM(sh.new_amount)
    FROM slash_history sh
    JOIN slashes s ON s.id = sh.slash_id
    JOIN restakes r ON r.id = s.restake_id
    WHERE r.point_id = ae.point_id
    AND sh.created_at <= ae.event_time
  ), 0) as total_slashes,
  CASE
    WHEN COALESCE((
      SELECT SUM(cred)
      FROM endorsements
      WHERE point_id = ae.point_id
      AND created_at <= ae.event_time
    ), 0) = 0 THEN 0
    WHEN COALESCE((
      SELECT SUM(cred)
      FROM endorsements
      WHERE point_id IN (
        SELECT newer_point_id FROM negations WHERE older_point_id = ae.point_id
        AND created_at <= ae.event_time
        UNION
        SELECT older_point_id FROM negations WHERE newer_point_id = ae.point_id
        AND created_at <= ae.event_time
      )
      AND created_at <= ae.event_time
    ), 0) = 0 THEN 100
    ELSE FLOOR(
      100.0 * COALESCE((
        SELECT SUM(cred)
        FROM endorsements
        WHERE point_id = ae.point_id
        AND created_at <= ae.event_time
      ), 0) / (
        COALESCE((
          SELECT SUM(cred)
          FROM endorsements
          WHERE point_id = ae.point_id
          AND created_at <= ae.event_time
        ), 0) + 
        COALESCE((
          SELECT SUM(cred)
          FROM endorsements
          WHERE point_id IN (
            SELECT newer_point_id FROM negations WHERE older_point_id = ae.point_id
            AND created_at <= ae.event_time
            UNION
            SELECT older_point_id FROM negations WHERE newer_point_id = ae.point_id
            AND created_at <= ae.event_time
          )
          AND created_at <= ae.event_time
        ), 0)
      )
    ) + GREATEST(0, 
      COALESCE((
        SELECT SUM(rh.new_amount)
        FROM restake_history rh
        JOIN restakes r ON r.id = rh.restake_id
        WHERE r.point_id = ae.point_id
        AND rh.created_at <= ae.event_time
      ), 0) - 
      GREATEST(
        COALESCE((
          SELECT SUM(
            LEAST(
              dh.new_amount,
              (
                SELECT COALESCE(SUM(rh2.new_amount), 0)
                FROM restake_history rh2
                JOIN restakes r2 ON r2.id = rh2.restake_id
                WHERE r2.point_id = ae.point_id
                AND rh2.created_at <= dh.created_at
              )
            )
          )
          FROM doubt_history dh
          JOIN doubts d ON d.id = dh.doubt_id
          WHERE d.point_id = ae.point_id
          AND dh.created_at <= ae.event_time
        ), 0),
        COALESCE((
          SELECT SUM(sh.new_amount)
          FROM slash_history sh
          JOIN slashes s ON s.id = sh.slash_id
          JOIN restakes r ON r.id = s.restake_id
          WHERE r.point_id = ae.point_id
          AND sh.created_at <= ae.event_time
        ), 0)
      )
    )
  END::integer as favor
FROM all_events ae
ORDER BY ae.event_time, ae.point_id;